config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("user/", include("user.urls", namespace="user")),
    path("orders/", include("order.urls", namespace="order")),
]

order/urls.py
from django.urls import path

from . import views

app_name = "order"
urlpatterns = [

    path("", views.orders_list, name="list"),
    path("create", views.create, name="create"),
    path("<int:orderPk>", views.orders_details, name="details"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from config import settings

from . import views

app_name = "user"

urlpatterns = [
    path("registration", views.register, name="registration"),
    path("login", views.loginUser, name="login"),
    path("logout", LogoutView.as_view(
        next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path(
        "cart",
        views.cart,
        name="cart",
    ),
    path(
        "addToCart/<int:productPk>",
        views.addToCart,
        name="addToCart",
    ),
    path(
        "increaseQuantity/<int:cartItemPk>",
        views.increaseQuantity,
        name="increaseQuantity",
    ),
    path(
        "decreaseQuantity/<int:cartItemPk>",
        views.decreaseQuantity,
        name="decreaseQuantity",
    ),
    path(
        "removeFromCart/<int:cartItemPk>",
        views.removeFromCart,
        name="removeFromCart",
    ),
]

order/models.py
from django.db import models

from product.models import Product
from user.models import User


class Order(models.Model):
    STATUS_CHOICES = [
        ("Pending", "Pending"),
        ("Approved", "Approved"),
        ("Declined", "Declined"),
        ("Shipped", "Shipped"),
        ("Delivered", "Delivered"),
    ]
    createdAt = models.DateTimeField(auto_now_add=True)
    totalPrice = models.DecimalField(decimal_places=2, max_digits=10)
    customerId = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="Pending")

    def __str__(self):
        return str(self.pk)


class OrderItem(models.Model):
    productId = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    orderId = models.ForeignKey(Order, on_delete=models.CASCADE)
    unitPrice = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return str(self.pk)

order/views.py
from django.shortcuts import redirect, render

from order.models import Order, OrderItem
from product.views import getUserCartItemsCount
from user.models import Cart, CartItem


def create(request):

    customer = request.user
    cart = Cart.objects.get(customer=customer)
    order = Order.objects.create(
        customerId=customer, totalPrice=cart.getTotal())
    cartItems = CartItem.objects.filter(cart=cart)
    for cartItem in cartItems:
        product = cartItem.product
        product.stockQuantity -= cartItem.quantity
        product.save()
        orderItem = OrderItem.objects.create(productId=product, quantity=cartItem.quantity,
                                             orderId=order, unitPrice=product.unitPrice)
        orderItem.save()
    order.save()
    cartItems.delete()
    return redirect("order:list")


def orders_list(request):
    status = request.GET.get("status")
    orders = Order.objects.filter(customerId=request.user)
    if status is not None and len(status) > 0:
        orders = orders.filter(status=status)
    return render(request, "orders.html", {"orders": orders, "cartCount": getUserCartItemsCount(request.user)})


def orders_details(request, orderPk):
    order = Order.objects.get(pk=orderPk)
    order.items = OrderItem.objects.filter(orderId=order)
    return render(request, "order-details.html", {"order": order, "cartCount": getUserCartItemsCount(request.user)})

order/templates/order-details.html
{% extends "base/base.html" %} {% block content %}
<h3>{{ order.id }}</h3>
<h3>{{ order.status }}</h3>
<div class="col">
  <div class="row">
    {% for orderItem in order.items %}
    <div class="col-4">
      <div class="card">
        <div class="card-header">
          <h3>{{ orderItem.product.nameEn }}</h3>
          <h3>{{ orderItem.quantity }}</h3>
        </div>
        <div class="card-actions">
          <a href="{{ product.get_absolute_url }}">View</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endfor %} {% endblock %}

order/templates/orders.html
{% extends "base/base.html" %} {% block content %}
<form>
  <h1 class="m-3">Orders</h1>
  <select class="m-3 " name="status" value="Pending">
    <option value="" >All</option>
    <option value="Pending" >Pending</option>
    <option value="Approved">Approved</option>
    <option value="Declined">Declined</option>
    <option value="Shipped" >Shipped</option>
    <option value="Delivered">Delivered</option>
  </select>
  <button type="submit">Apply</button>
</form>
<div class="col">
  <div class="row">
    {% for order in orders %}
    <div class="col-12 col-sm-4">
      <div class="card">
        <div class="card-header">
          <h3>Order number: {{ order.id }}</h3>
          <h3>Status: {{ order.status }}</h3>
        </div>
        <div class="card-actions p-2">
          <a href="{% url 'order:details' order.id %}"> View</a>
        </div>
      </div>
    </div>
  </div>
</div>
{%empty%}
<h1>No Orders Yet</h1>
{% endfor %} {% endblock %}