config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("user/", include("user.urls", namespace="user")),
    path("orders/", include("order.urls", namespace="order")),
]

product/urls.py
from django.urls import path

from . import views

app_name = "product"
urlpatterns = [
    path("", views.product_list, name="list"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from config import settings

from . import views

app_name = "user"

urlpatterns = [
    path("registration", views.register, name="registration"),
    path("login", views.loginUser, name="login"),
    path("logout", LogoutView.as_view(
        next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path(
        "cart",
        views.cart,
        name="cart",
    ),
    path(
        "addToCart/<int:productPk>",
        views.addToCart,
        name="addToCart",
    ),
    path(
        "increaseQuantity/<int:cartItemPk>",
        views.increaseQuantity,
        name="increaseQuantity",
    ),
    path(
        "decreaseQuantity/<int:cartItemPk>",
        views.decreaseQuantity,
        name="decreaseQuantity",
    ),
    path(
        "removeFromCart/<int:cartItemPk>",
        views.removeFromCart,
        name="removeFromCart",
    ),
]

product/models.py
from django.db import models

# Product (ID, NameEn, NameAr, UnitPrice, StockQuantity, CategoryID)


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    nameEn = models.CharField(max_length=200)
    nameAr = models.CharField(max_length=200)
    unitPrice = models.DecimalField(max_digits=10, decimal_places=2)
    stockQuantity = models.IntegerField()
    categoryId = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.pk)

product/views.py
import functools
from urllib import request
from django.shortcuts import render

from product.models import Category, Product
from user.models import Cart, CartItem, User

app_name = "product"


def getQueryParameterIfDefined(request, key):
    value = request.GET.get(key)
    if value is not None and len(value) > 0:
        return value
# Create your views here.


def product_list(request):

    # view all products
    products = Product.objects.all()

    # filter products by Category
    category = getQueryParameterIfDefined(request, "category")
    if category:
        products = products.filter(categoryId__name=category)

    # filter products by price range
    min_price = getQueryParameterIfDefined(request, "min_price")
    if min_price:
        products = products.filter(
            unitPrice__gte=(int(min_price)))
    max_price = getQueryParameterIfDefined(request, 'max_price')
    if max_price:
        products = products.filter(
            unitPrice__lte=(int(max_price)))

    # filter products by search name
    searchKeyword = getQueryParameterIfDefined(request, 'searchKeyword')
    if searchKeyword:
        products = products.filter(nameEn__icontains=searchKeyword.strip())

    user = getUserFromRequest(request)
    cartItems = getUserCartItems(user)
    for product in products:
        for cartItem in cartItems:
            if product.pk == cartItem.product.pk:
                product.cartItem = cartItem
    context = {"cartCount": getUserCartItemsCount(
        user), "products": products, "categories": Category.objects.all()}
    return render(request, "products.html", context)


def getUserFromRequest(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.pk)
        print("user", user)
        return user


def getUserCartItemsCount(user):
    if user is None:
        return 0
    cart = Cart.objects.get(customer=user)
    return len(CartItem.objects.filter(cart=cart))


def getUserCartItems(user):
    if user is None:
        return list()
    cart = Cart.objects.get(customer=user)
    return CartItem.objects.filter(cart=cart)

product/templates/products.html
{% extends "base/base.html" %} {% block content %}
<div class="card">
  <div class="card-header">
    <h6>Filters</h6>
  </div>
  <form id="products-filters" class="p-5">
    <h6 >Price Range</h6>
    <div class="d-grid gap-3">
      <div>
        <label for="min_price">Min Price</label>
        <input type="number" id="min_price" name="min_price" />
      </div>
      <div>
        <label for="max_price">Max Price</label>
        <input type="number" id="max_price" name="max_price" />
      </div>
      <button type="submit">Apply</button>

      
    </div>
    <hr />
    <h6>Categories</h6>
    <div class="d-flex">
      <div class="form-check form-check-inline">
        <input
          type="radio"
          class="form-check-input"
          id="all"
          name="category"
          value=""
          checked
        />
        <label for="all" class="form-check-label">All</label>
      </div>

      {% for category in categories %}
      <div class="form-check form-check-inline">
        <input
          type="radio"
          id="{{category.name}}"
          name="category"
          value="{{category.name}}"
          class="form-check-input"
        />
        <label class="form-check-label" for="{{category.name}}"
          >{{category.name}}</label
        >
      </div>
      {% endfor %}
    </div>
  </form>
</div>

  <div class="row m-2">
    {% for product in products %}
    <div class="col-12 col-sm-4 p-0">
      <div class="card">
        <div class="card-header">
          <h3>{{ product.nameEn }}</h3>
        </div>
        <div class="card-content p-2">
          <h3>Price: {{ product.unitPrice }} EGP</h3>
        </div>
        {%if product.cartItem%}
        <div class="p-2 d-flex gap-2 justify-content-center align-items-center">
          {%if product.cartItem.quantity == 1%}
          <a
            class="btn btn-danger btn-sm p-1"
            href="{% url 'user:removeFromCart' product.cartItem.id %}?source=product:list"
            >Remove From Cart</a
          >
          {%else%}
          <a
            class="btn btn-danger btn-sm p-1"
            href="{% url 'user:decreaseQuantity' product.cartItem.id %}?source=product:list"
            >Decrease Quantity</a
          >
          {%endif%}
          <p class="px-2 pt-3">{{product.cartItem.quantity}}</p>
          <a
            class="btn btn-primary btn-sm p-1"
            href="{% url 'user:increaseQuantity' product.cartItem.id %}?source=product:list
            "
            >Increase Quantity</a
          >
        </div>
        {%elif product.stockQuantity > 0%}
        <div class="p-2 d-flex justify-content-end">
          <a
            class="btn btn-primary"
            href="{% url 'user:addToCart' product.id %}?source=product:list"
            >Add To Cart</a
          >
        </div>
        {%else%}
        <div class="p-2 d-flex justify-content-end">
          <p>Out of stock</p>
        </div>
        {%endif%}
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}