config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="product")),
    path("user/", include("user.urls", namespace="user")),
    path("orders/", include("order.urls", namespace="order")),
]

order/urls.py
from django.urls import path

from . import views

app_name = "order"
urlpatterns = [

    path("", views.orders_list, name="list"),
    path("create", views.create, name="create"),
    path("<int:orderPk>", views.orders_details, name="details"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView

from config import settings

from . import views

app_name = "user"

urlpatterns = [
    path("registration", views.register, name="registration"),
    path("login", views.loginUser, name="login"),
    path("logout", LogoutView.as_view(
        next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path(
        "cart",
        views.cart,
        name="cart",
    ),
    path(
        "addToCart/<int:productPk>",
        views.addToCart,
        name="addToCart",
    ),
    path(
        "increaseQuantity/<int:cartItemPk>",
        views.increaseQuantity,
        name="increaseQuantity",
    ),
    path(
        "decreaseQuantity/<int:cartItemPk>",
        views.decreaseQuantity,
        name="decreaseQuantity",
    ),
    path(
        "removeFromCart/<int:cartItemPk>",
        views.removeFromCart,
        name="removeFromCart",
    ),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

core/templates/base/base.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Django E-commerce{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>
    <div class="site-wrap">
        {% include 'base/navbar.html' %}
        {% block content %}
        {% endblock %}
        {% include 'base/footer.html' %}
    </div>

    <script src="{% static "js/index.js" %}"></script>
</body>
</html>

core/templates/base/footer.html
    <footer class="site-footer border-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="footer-heading mb-4">Navigations</h3>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Sell online</a></li>
                                <li><a href="#">Features</a></li>
                                <li><a href="#">Shopping cart</a></li>
                                <li><a href="#">Store builder</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Mobile commerce</a></li>
                                <li><a href="#">Dropshipping</a></li>
                                <li><a href="#">Website development</a></li>
                            </ul>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <ul class="list-unstyled">
                                <li><a href="#">Point of sale</a></li>
                                <li><a href="#">Hardware</a></li>
                                <li><a href="#">Software</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
                    <h3 class="footer-heading mb-4">Promo</h3>
                    <a href="#" class="block-6">
                        <h3 class="font-weight-light  mb-0">Finding Your Perfect Shoes</h3>
                        <p>Promo from nuary 15 &mdash; 25, 2019</p>
                    </a>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-5 mb-5">
                        <h3 class="footer-heading mb-4">Contact Info</h3>
                        <ul class="list-unstyled">
                            <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                            <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                            <li class="email">emailaddress@domain.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

core/templates/base/navbar.html
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-12 col-md-4 order-2 order-md-1 col-sm-6">
                        <form action="/" class="site-block-top-search" >
                            <span class="icon icon-search2"></span>
                            <input type="text" class="form-control text-center p-0" placeholder="Search" name="searchKeyword">
                        </form>
                    </div>

                    <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                        <div class="site-logo">
                            <a href="/" class="js-logo-clone">E-commerce</a>
                        </div>
                    </div>

                    <div class="col-12 col-md-4 order-3 order-md-3 text-right col-sm-6 text-center mt-3">
                        <div class="site-top-icons">
                            <ul>
                                {%if user and user.is_authenticated%}
                                <li><p>Hello: {{user.fullName}} , </p></li>
                                <li><a href="{% url "user:logout" %}">Logout</a></li>
                                <li>
                                    <a href="{% url "user:cart" %}" class="site-cart">
                                        <p>,Cart</p>
                                        <span class="count">
                                            {{cartCount}}
                                        </span>
                                    </a>
                                </li>
                                {%else%}
                                <li><a href="{% url "user:registration" %}">Register</a></li>
                                <li><a href="{% url "user:login" %}">Login</a></li>
                                {%endif%}
                                <li class="d-inline-block d-md-none ml-md-0"><a href="#"
                                        class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <nav class="site-navigation text-right text-md-center" role="navigation">
            <div class="container">
                <ul class="site-menu js-clone-nav d-none d-md-block">
                
                    <li><a href="{% url "product:list" %}">Home</a></li>
                    {%if user and user.is_authenticated%}
                    <li><a href="{% url "order:list" %}">Orders</a></li>
                    {%endif%}
                </ul>
            </div>
        </nav>
    </header>